---
# tasks file for configure_nginx
- name: Check nginx.conf exists
  stat:
    path: /etc/nginx/nginx.conf
  register: nginx_ex

- name: Install nginx
  yum:
    name:
      - nginx
    state: present
  when: nginx_ex.stat.exists == false
  notify: nginx_tune




